# Generated by Django 4.1.5 on 2023-01-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='placed_at',
        ),
        migrations.AddField(
            model_name='order',
            name='flavour',
            field=models.CharField(default='-', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In_Transit'), ('DELIVERED', 'delivered')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra_Large')], default='SMALL', max_length=25),
        ),
    ]
